### ISSUE TITLE
Add ability to handle default routing for backend

### ISSUE THREAD

**Issue by jimfaut-okta** [jimfaut-okta/SATOSA#1]
The current implementation of DecideBackendByRequester has a fixed map of requestor to backend.  There is no ability to define a default routing, so each requester must be listed individually.  This is not very flexible and is difficult to manage for a large number of requesters.  A default routing will make it easier to manage the exceptions to the routing rule.

Add the ability to recognize "default" as a key in the routing configuration file.  For example:

```
module: satosa.micro_services.custom_routing.DecideBackendByRequester
name: RequesterRouter
config:
  requester_mapping:
    default: Saml2 # map SAML entity with entity id 'requester1' to backend with name 'SAML2'
```
